Add Neon implementation of SIMD classes.
Lightricks/dlib pull request #3
Opened 2016-11-09 10:13 UTC by gershonho

2016-11-09 13:41 UTC, StatusReport requested changes
Are you sure this is the branch with the latest changes?

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4f.h
> +          float __attribute__((aligned (16))) data[4] = { r0, r1, r2, r3 };
Inconsistent indentation.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +//#elif defined(DLIB_HAVE_NEON)
Remove (why BTW?).

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +		return vmaxq_s32(lhs, rhs);
Indentation.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +		//int32x4_t result = vdupq_n_s32(0);
Remove (why?).

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +		//int32x4_t result = vdupq_n_s32(0);
Remove (why is this commented out?).

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +        return _mm_mullo_epi32(lhs, rhs);
This line has not changed.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> -        return _mm_and_si128(lhs, rhs);
Same.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +		return vaddq_s32(lhs, rhs);
Indentation. Please keep consistent to the file's indentation.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4i.h
> +	class simd4i
Indentation.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4f.h
> -
Let's do minimal changes, so remove.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4f.h
> +      std::cout << "ceil!" << std::endl;
Remove.

2016-11-09 13:41 UTC, StatusReport commented on dlib/simd/simd4f.h
> +      std::cout << "floor!" << std::endl;
Remove.

2016-11-09 14:14 UTC, gershonho commented on dlib/simd/simd4f.h
> +          float __attribute__((aligned (16))) data[4] = { r0, r1, r2, r3 };
Done.

2016-11-09 14:15 UTC, gershonho commented on dlib/simd/simd4f.h
> +      std::cout << "ceil!" << std::endl;
Done.

2016-11-09 14:15 UTC, gershonho commented on dlib/simd/simd4f.h
> +      std::cout << "floor!" << std::endl;
Done.

2016-11-09 14:18 UTC, gershonho commented on dlib/simd/simd4f.h
> -
Done.

2016-11-09 14:19 UTC, gershonho commented on dlib/simd/simd4i.h
> +	class simd4i
Done.

2016-11-09 14:24 UTC, gershonho commented on dlib/simd/simd4i.h
> +		return vaddq_s32(lhs, rhs);
Done.

2016-11-09 14:25 UTC, gershonho commented on dlib/simd/simd4i.h
> +        return _mm_mullo_epi32(lhs, rhs);
Correct.

2016-11-09 14:35 UTC, gershonho commented on dlib/simd/simd4i.h
> +		//int32x4_t result = vdupq_n_s32(0);
Done.

2016-11-09 14:35 UTC, gershonho commented on dlib/simd/simd4i.h
> +		//int32x4_t result = vdupq_n_s32(0);
Done.

2016-11-09 14:36 UTC, gershonho commented on dlib/simd/simd4i.h
> +		return vmaxq_s32(lhs, rhs);
Done.

2016-11-09 15:03 UTC, gershonho commented on dlib/simd/simd4i.h
> +//#elif defined(DLIB_HAVE_NEON)
Done.

2016-11-09 17:04 UTC, gershonho commented
Done. This is the latest version (it contains simd4f_bool based on uint32x4_t).

2016-11-09 20:50 UTC, StatusReport requested changes
Round.

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4f.h
> +					  1.0f/_lhs[1],
Indentation.

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4f.h
> +      float32x4_t x1 = vmaxq_f32(item, vdupq_n_f32(FLT_MIN));
Indentation.

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4f.h
> +		return (float32x4_t)vorrq_s32(
Indentation.

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4i.h
> +        return _mm_mullo_epi32(lhs, rhs);
So why do we have a diff here?

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4f.h
> +#elif defined(DLIB_HAVE_NEON) //TODO : optz
remove comment

2016-11-09 20:50 UTC, StatusReport commented on dlib/simd/simd4f.h
> +		float _lhs[4]; item.store(_lhs);
Indentation + newline.

2016-11-10 06:53 UTC, gershonho commented on dlib/simd/simd4f.h
> +		float _lhs[4]; item.store(_lhs);
Done.

2016-11-10 06:53 UTC, gershonho commented on dlib/simd/simd4f.h
> +					  1.0f/_lhs[1],
Done.

2016-11-10 06:53 UTC, gershonho commented on dlib/simd/simd4f.h
> +      float32x4_t x1 = vmaxq_f32(item, vdupq_n_f32(FLT_MIN));
Done.

2016-11-10 06:54 UTC, gershonho commented on dlib/simd/simd4f.h
> +#elif defined(DLIB_HAVE_NEON) //TODO : optz
Done.

2016-11-10 06:56 UTC, gershonho commented on dlib/simd/simd4f.h
> +		return (float32x4_t)vorrq_s32(
Done.

2016-11-10 07:07 UTC, gershonho commented on dlib/simd/simd4i.h
> +        return _mm_mullo_epi32(lhs, rhs);
The old version has a trailing blank. The new version has this trailing blank dropped (presumably by Xcode).

2016-11-10 07:08 UTC, gershonho commented on dlib/simd/simd4i.h
> -        return _mm_and_si128(lhs, rhs);
Same.

2016-11-10 07:37 UTC, StatusReport commented
Squash.

2016-11-10 07:49 UTC, gershonho commented
Done.

2016-11-10 07:52 UTC, StatusReport approved these changes

2016-11-10 07:53 UTC, merged